CREATE DATABASE db_Library

USE db_Library
GO


CREATE TABLE tbl_libraryBranch (
	BranchID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BranchName VARCHAR(50) NOT NULL,
	BranchAddress VARCHAR(100) NOT NULL
);

CREATE TABLE tbl_libraryBooks (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (101, 1),
	PublisherName VARCHAR(50) NOT NULL,
	Title VARCHAR(100) NOT NULL
);

CREATE TABLE tbl_borrowers (
	CardNo INT PRIMARY KEY NOT NULL IDENTITY (10001, 1),
	FullName VARCHAR(60) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Phone VARCHAR(30) NOT NULL
);

CREATE TABLE tbl_bookCopies (
	BookID INT NOT NULL CONSTRAINT fk_book_id FOREIGN KEY REFERENCES tbl_libraryBooks(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT fk_branch_id FOREIGN KEY REFERENCES tbl_libraryBranch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	Number_Of_Copies INT NOT NULL
);

CREATE TABLE tbl_bookLoans (
	CardNo INT NOT NULL CONSTRAINT fk_card_id FOREIGN KEY REFERENCES tbl_borrowers(CardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	BookID INT NOT NULL CONSTRAINT fk_books_id FOREIGN KEY REFERENCES tbl_libraryBooks(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT fk_branches_id FOREIGN KEY REFERENCES tbl_libraryBranch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut DATE NOT NULL,
	DateDue DATE NOT NULL
);

CREATE TABLE tbl_publishers (
	PublisherName VARCHAR(50) NOT NULL,
	Address VARCHAR(75) NOT NULL,
	Phone VARCHAR(30) NOT NULL
);

CREATE TABLE tbl_authors (
	BookID INT NOT NULL CONSTRAINT fk_book_auth_id FOREIGN KEY REFERENCES tbl_libraryBooks(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName VARCHAR(50) NOT NULL
);